- name: Create rke nginx servers
  os_server:
    cloud: default
    name: nginx
    image: k8s_ubuntu_16.04
    key_name: rancher_key
    timeout: 200
    flavor: test
    auto_ip: no
    nics:
      - port-name: nginx
    userdata: |
      #cloud-config
      chpasswd:
        list: |
          ubuntu:openstack
        expire: False
      ssh_pwauth: true
      package_upgrade: true
      manage_etc_hosts: true

- name: Create rke master1 servers
  os_server:
    cloud: default
    name: master1
    image: k8s_ubuntu_16.04
    key_name: rancher_key
    timeout: 200
    flavor: rancher
    auto_ip: no
    nics:
      - port-name: rancher-master-1
    userdata: |
      #cloud-config
      chpasswd:
        list: |
          ubuntu:openstack
        expire: False
      ssh_pwauth: true
      packages:
        - sshpass
        - python-pip
      package_upgrade: true
      manage_etc_hosts: true
      runcmd:
         -  'su -c "pip install ansible"'
         -  'su -c "git clone https://github.com/dommgifer/rancher2.0-ha.git /home/ubuntu/rancher2.0-ha"'
         -  'su -c "mkdir /etc/ansible"'
         -  'su -c "cp /home/ubuntu/rancher2.0-ha/ansible.cfg /etc/ansible/"'
         -  'su -c "ansible-playbook -i /home/ubuntu/rancher2.0-ha/inventory /home/ubuntu/rancher2.0-ha/python.yml"'
         -  'su -c "ansible-playbook -i /home/ubuntu/rancher2.0-ha/inventory /home/ubuntu/rancher2.0-ha/deploy.yml"'

- name: Create rke master2 servers
  os_server:
    cloud: default
    name: master2
    image: k8s_ubuntu_16.04
    key_name: rancher_key
    timeout: 200
    flavor: rancher
    auto_ip: no
    nics:
      - port-name: rancher-master-2
    userdata: |
      #cloud-config
      chpasswd:
        list: |
          ubuntu:openstack
        expire: False
      ssh_pwauth: true
      manage_etc_hosts: true


- name: Create rke master3 servers
  os_server:
    cloud: default
    name: master3
    image: k8s_ubuntu_16.04
    key_name: rancher_key
    timeout: 200
    flavor: rancher
    auto_ip: no
    nics:
      - port-name: rancher-master-3
    userdata: |
      #cloud-config
      chpasswd:
        list: |
          ubuntu:openstack
        expire: False
      ssh_pwauth: true
      manage_etc_hosts: true
